format_version: v1.0
type: GeneratorComponent
attributes: {id: tcpipNetConfig}
children:
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: tcpipNetConfig}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_DNS_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: 192.168.1.1}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_GATEWAY_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: 192.168.1.1}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_HOST_NAME_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: MCHPBOARD_W}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_INTERFACE_NAME_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: PIC32MZW1}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_IP_ADDRESS_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: 0.0.0.0}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_MAC_DRIVER_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: WDRV_PIC32MZW1_MACObject}
      - type: Boolean
        attributes: {id: TCPIP_STACK_NETWORK_CONFIG_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: 'true'}
      - type: Integer
        attributes: {id: TCPIP_STACK_NETWORK_CONFIG_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: '0'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: NETCONFIG_MAC_Dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drvWifiPic32mzw1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: libdrvPic32mzw1Mac}
- type: ElementPosition
  attributes: {x: '541', y: '45', id: tcpipNetConfig}
