format_version: v1.0
type: UniqueComponent
attributes: {id: tcpip_apps_config}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DHCP_CLIENT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DHCP_SERVER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DHCP_SERVER_V2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DNS_CLIENT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DNS_SERVER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_SNTP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpip_apps_config, value: 'true'}
- type: ElementPosition
  attributes: {x: '20', y: '20', id: tcpip_apps_config}
